apiVersion: v1
kind: Service
metadata:
  name: demo-nodeport-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
