---
apiVersion: v1
kind: ClusterConfig
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::332670553932:policy/AWSLoadBalancerControllerPolicy"
    tags:
      Owner: "John Doe"
      Team: "Some Team"
